# Generated by Django 5.0.1 on 2024-01-16 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(default=1, verbose_name='Data do Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
